import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import spotifyLogin from '../lib/spotify-login'
import logo from '../public/Spotify_Logo_White.png'

export default function Home({appID, redirect_uri}) {
  return (
    <>
      <Head>
        <title>Teletext Spotify Top 10</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <Image src={logo} className={styles.logo} />
        <h1>Teletext Spotify Top 10</h1>
        <br />
        <h2>Display my top 10 Spotify tracks in the style of the 90s internet predecessor, teletext.</h2>
        <br />
          <button className={styles.button} type="button" onClick={() => spotifyLogin(appID, redirect_uri)}>Login</button>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
     const clientId = process.env.CLIENT_ID
     const redirect_uri = process.env.REDIRECT_URL

     return {
      props: {
        appID : clientId,
        redirect_uri : redirect_uri
      } 
     }
}