import Head from 'next/head'
import Image from 'next/image'                        
import spotifyLogin from '../lib/spotify-login'
import Tracks from '../components/Tracks'
import { useEffect, useState, useRef } from 'react'
import styles from '../styles/Totp.module.scss'
import dynamic from 'next/dynamic'
import Title from '../components/Title'
import Footer from '../components/Footer'
import {toPng}  from 'html-to-image'

const ChartHeader = dynamic(() => import("../components/ChartHeader"), {ssr: false})


const getReturnedParamsFromSpotifyAuth = (hash) => {
    const stringAfterHashtag = hash.substring(1)
    const paramsInUrl = stringAfterHashtag.split("&")
    const paramsSplitUp = paramsInUrl.reduce((accumulator,currentValue) => {
        const [key, value] = currentValue.split("=")
        accumulator[key] = value
        
        return accumulator
    }, {})
    return paramsSplitUp
}



export default function Totp() {
    
    const [token, setToken] = useState(null)
    useEffect(() => {
        if(window.location.hash) {
            const {access_token} = getReturnedParamsFromSpotifyAuth(window.location.hash)
            setToken(access_token)
        }
    }, [ token ])

    const domEl = useRef(null)

    const downloadAsImage = async () => {
    const dataUrl = await toPng(
      domEl.current, { 
      backgroundColor: "#000000",
      canvasHeight: 500,
      canvasWidth: 500,
     
    })
    
    // download Image
    const link = document.createElement('a')
    link.download = "spotify-teletext.png"
    link.href = dataUrl;
    link.click()
}

  return (
    <>
      <Head>
        <title>Spotify Test - TOTP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} i>
        <div id="main" ref={domEl}>
        <ChartHeader />
        <Title />
        <br />
        <h2 className={styles.redBorder}>My top 10 tracks on Spotify!</h2>
        <br />
        {
         token &&   
          <Tracks
        token={token} />  
        }
        <Footer />
        </div>
        <button onClick={downloadAsImage}>Download</button>
      </main>
    </>
  )
}
