import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import spotifyLogin from '../lib/spotify-login'
import Tracks from '../components/Tracks'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })


const getReturnedParamsFromSpotifyAuth = (hash) => {
    const stringAfterHashtag = hash.substring(1)
    const paramsInUrl = stringAfterHashtag.split("&")
    const paramsSplitUp = paramsInUrl.reduce((accumulator,currentValue) => {
        const [key, value] = currentValue.split("=")
        accumulator[key] = value
        
        return accumulator
    }, {})
    return paramsSplitUp
}


export default function Totp() {
    
    const [token, setToken] = useState(null)
    useEffect(() => {
        if(window.location.hash) {
            const {access_token} = getReturnedParamsFromSpotifyAuth(window.location.hash)
            setToken(access_token)
        }
    }, [ token ])
  return (
    <>
      <Head>
        <title>Spotify Test - TOTP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={inter.className}>
        <h1>Spotify API Test</h1>
        <br />
        <h2>Display my top played tracks from the last 6 months</h2>
        <br />
        {
         token &&   
          <Tracks
        token={token} />  
        }
        
        </div>
      </main>
    </>
  )
}
